package pl.polsl.java.lab3.tomasz.domaracki.JavaBillsCollectionView;

/**
 * Class implements handling for elements in program menu
 * 
 * @author tomaszdomaracki
 * @version 1.0.0
 */

public class AppLogger extends javax.swing.JFrame {

    private String loggerText;
    private static AppLogger instance = null;
    /**
     * Creates new form AppLogger
     */
    private AppLogger() {
        initComponents();
        loggerText = "";
    }

        
    public static AppLogger getInstance(){
        if (instance == null){
            instance = new AppLogger();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollLogger = new javax.swing.JScrollPane();
        loggerTextArea = new javax.swing.JTextArea();
        clearLogButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Server logger");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(541, 178));

        loggerTextArea.setEditable(false);
        loggerTextArea.setColumns(20);
        loggerTextArea.setRows(5);
        scrollLogger.setViewportView(loggerTextArea);

        clearLogButton.setText("Clear Log");
        clearLogButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clearLogButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearLogButton)
                .addContainerGap())
            .addComponent(scrollLogger, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollLogger, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearLogButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearLogButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearLogButtonMouseReleased
        loggerText ="";
        loggerTextArea.setText(loggerText);
    }//GEN-LAST:event_clearLogButtonMouseReleased
    
    public void addTextToLog(String text){
        if (loggerText.equals("")){
            loggerText = text;
        }
        else{
            loggerText += "\n";
            loggerText += text;
        }
        loggerTextArea.setText(loggerText);
    }
    
    public String getLogText(){
        return loggerText;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearLogButton;
    private javax.swing.JTextArea loggerTextArea;
    private javax.swing.JScrollPane scrollLogger;
    // End of variables declaration//GEN-END:variables
}
