package pl.polsl.java.lab3.tomasz.domaracki.JavaBillsCollectionView;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JSplitPane;
import javax.swing.KeyStroke;
import pl.polsl.java.lab3.tomasz.domaracki.JavaBillsCollectionModel.Bill;

import pl.polsl.java.lab3.tomasz.domaracki.JavaBillsCollectionController.BillController;
import pl.polsl.java.lab3.tomasz.domaracki.JavaBillsCollectionController.DatabaseController;

/**
 * Class implements dialog showing when editing existing bill in database
 * 
 * @author tomaszdomaracki
 * @version 1.0.0
 */
public class EditBillDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    private final MenuItemsHandling menuItems;
    private final JSplitPane parentLayout;
    private File selectedBillPhoto;
    private BufferedImage billImage;
    private DatabaseController db;
    private BillController billController;
    private Bill selectedBill;
    
    /**
     * Creates new form AddNewBillDialog
     */
    public EditBillDialog(java.awt.Frame parent, boolean modal, JSplitPane parentLayout, DatabaseController db) {
        super(parent, modal);
        initComponents();
        menuItems = new MenuItemsHandling(null);
        this.parentLayout = parentLayout;
        this.db = db;
        billController = new BillController();
        selectedBillPhoto = null;
        
        this.setTitle("Bill editor");
        
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        photoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billNameTextBox = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        billDateTextBox = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        durationOfGuaranteeTextBox = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        dateOnBillErrorLabel = new javax.swing.JLabel();
        durationErrorLabel = new javax.swing.JLabel();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(billNameTextBox);

        jLabel1.setText("Device name on the bill:");

        jScrollPane2.setViewportView(billDateTextBox);

        jLabel2.setText("Date on bill: [yyyy/MM/dd]");

        jScrollPane3.setViewportView(durationOfGuaranteeTextBox);

        jLabel3.setText("Duration of the guarantee:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(450, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(dateOnBillErrorLabel)
                                    .addComponent(durationErrorLabel))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dateOnBillErrorLabel)
                        .addGap(18, 18, 18)
                        .addComponent(durationErrorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(50, Short.MAX_VALUE)
                        .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Do actions when user clicks OK button in dialog
     * 
     * @param evt user event
     */
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        boolean inputError = false;
        
        if(selectedBillPhoto != null){
            String billName = billNameTextBox.getText();
            String dateOfGuarantee = billDateTextBox.getText();
            String durationOfGuarantee = durationOfGuaranteeTextBox.getText();
            VerifyUserInput verifier = new VerifyUserInput(durationOfGuarantee, dateOfGuarantee);
            if(!verifier.verifyDateOfGuarantee()){
                dateOnBillErrorLabel.setText("Verify date on bill. [yyyy/MM/dd]");
                inputError = true;
            }
            else{
                dateOnBillErrorLabel.setText("");
            }
            if(!verifier.verifyDurationOfGuarantee()){
                durationErrorLabel.setText("Verify duration of guarantee. Must be a number.");
                inputError = true;
            }
            else{
                durationErrorLabel.setText("");
            }
            if (inputError){
                return;
            }
            int durationOfGuaranteeNumber = Integer.parseInt(durationOfGuarantee);
            
            db.deleteFromDatabase(selectedBill);
            db.addToDatabase((Object) billController.createNewBill(billName, dateOfGuarantee, selectedBillPhoto, durationOfGuaranteeNumber));
            doClose(RET_OK);
        }
        else{
            doClose(RET_CANCEL);
        }
    }//GEN-LAST:event_okButtonActionPerformed
    
    /**
     * Do actions when user clicks CANCEL button in dialog
     * 
     * @param evt 
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    /**
     * Closes EditBillDialog
     * 
     * @param retStatus return which button was clicked
     */
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
    }
    
    /**
     * 
     * Shows bill image in editing dialog
     */
    public void showBillPhoto(){
        billImage = null;
        try{
            billImage = ImageIO.read(selectedBillPhoto);
        }
        catch(IOException e){
            System.err.println(e.getMessage());
        }
        
        BufferedImage resizedBillPhoto = resizeImage(billImage);
        photoLabel.setIcon(new ImageIcon(resizedBillPhoto));
    }
    
    /**
     * Changes size of given image to suit window size
     * 
     * @param originalImage image to change size
     * @return image with changed dimensions
     */
    private BufferedImage resizeImage(BufferedImage originalImage){
        double factorFromWidth =  (double)originalImage.getWidth() / (double)photoLabel.getWidth();
        double factorFromHeight =  (double)originalImage.getHeight()/ (double)photoLabel.getHeight();
        double factor = 1.0;
        if (factorFromHeight > factorFromWidth){
            factor = factorFromHeight;
        }
        else{
            factor = factorFromWidth;
        }
        
        int IMG_WIDTH = (int)((double)originalImage.getWidth() / factor);
        int IMG_HEIGHT = (int)((double)originalImage.getHeight() / factor);//photoLabel.getHeight();// / originalImage.getHeight();
        
	BufferedImage resizedImage = new BufferedImage(IMG_WIDTH, IMG_HEIGHT, originalImage.getType());
	Graphics2D g = resizedImage.createGraphics();
	g.drawImage(originalImage, 0, 0, IMG_WIDTH, IMG_HEIGHT, null);
	g.dispose();

	return resizedImage;
    }
    
    /**
     * Initialize selectedBill, and its photo
     * 
     * @param selectedBill 
     */
    public void setSelectedBill(Bill selectedBill){
        this.selectedBill = selectedBill;
        selectedBillPhoto = selectedBill.getPhotoFile();
    }
    
    /**
     * 
     * Initizalize textboxes in bill editing dialog
     */
    public void initTextBoxes(){
        billNameTextBox.setText(selectedBill.getName());
        billDateTextBox.setText(selectedBill.getDateOfGuaranteeInInputFormat());
        Integer guaranteeDuration = selectedBill.getGuaranteeDuration();
        durationOfGuaranteeTextBox.setText(guaranteeDuration.toString());
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane billDateTextBox;
    private javax.swing.JTextPane billNameTextBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel dateOnBillErrorLabel;
    private javax.swing.JLabel durationErrorLabel;
    private javax.swing.JTextPane durationOfGuaranteeTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel photoLabel;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
